
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hamza
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anaekran_panel = new javax.swing.JPanel();
        aekran_kul_adı = new javax.swing.JLabel();
        aekran_sifre = new javax.swing.JLabel();
        aekran_kayıtol = new javax.swing.JButton();
        aekran_giris = new javax.swing.JButton();
        aekran_kadi_alani = new javax.swing.JTextField();
        aekran_sifre_alani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATM PROGRAMI");
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));

        aekran_kul_adı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aekran_kul_adı.setText("Kullanıcı Adı : ");

        aekran_sifre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aekran_sifre.setText("          Şifre :");

        aekran_kayıtol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aekran_kayıtol.setText("KAYIT OL");
        aekran_kayıtol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aekran_kayıtolActionPerformed(evt);
            }
        });

        aekran_giris.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aekran_giris.setText("GİRİŞ");
        aekran_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aekran_girisActionPerformed(evt);
            }
        });

        aekran_kadi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aekran_kadi_alaniActionPerformed(evt);
            }
        });

        aekran_sifre_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aekran_sifre_alaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anaekran_panelLayout = new javax.swing.GroupLayout(anaekran_panel);
        anaekran_panel.setLayout(anaekran_panelLayout);
        anaekran_panelLayout.setHorizontalGroup(
            anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaekran_panelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aekran_kayıtol, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aekran_kul_adı, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(aekran_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anaekran_panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aekran_sifre_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(aekran_kadi_alani)))
                    .addGroup(anaekran_panelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(aekran_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        anaekran_panelLayout.setVerticalGroup(
            anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaekran_panelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aekran_kul_adı, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aekran_kadi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aekran_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aekran_sifre_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(anaekran_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aekran_kayıtol, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(aekran_giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaekran_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaekran_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aekran_sifre_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aekran_sifre_alaniActionPerformed
          
    }//GEN-LAST:event_aekran_sifre_alaniActionPerformed

    private void aekran_kadi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aekran_kadi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aekran_kadi_alaniActionPerformed

    private void aekran_kayıtolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aekran_kayıtolActionPerformed
        
        KayitEkrani kayitekrani = new KayitEkrani();
       
        
       kayitekrani.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_aekran_kayıtolActionPerformed

    private void aekran_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aekran_girisActionPerformed
     
        try {
            KayitEt kayitet = new KayitEt(aekran_kul_adı.getText(), aekran_sifre_alani.getText());
            
            if(kayitet.kontrolEt()==false){
                
                
                
                JOptionPane.showMessageDialog(AnaEkran.this,"Giriş Başarılı");
                
                setVisible(false);
                
            }
            else{
                JOptionPane.showMessageDialog(AnaEkran.this,"Kullanıcı Bulunamadı. Lütfen Kayıt Olunuz !!");
            }
            
            
            
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_aekran_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aekran_giris;
    private javax.swing.JTextField aekran_kadi_alani;
    private javax.swing.JButton aekran_kayıtol;
    private javax.swing.JLabel aekran_kul_adı;
    private javax.swing.JLabel aekran_sifre;
    private javax.swing.JTextField aekran_sifre_alani;
    private javax.swing.JPanel anaekran_panel;
    // End of variables declaration//GEN-END:variables
}
