
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hamza
 */
public class KayitEkrani extends javax.swing.JFrame {

    /**
     * Creates new form KayitEkrani
     */
    public KayitEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aekran_kul_adı = new javax.swing.JLabel();
        aekran_sifre = new javax.swing.JLabel();
        kayitet_kadi_alani = new javax.swing.JTextField();
        kayitet_sifre_alani = new javax.swing.JTextField();
        kayitet_kayıtol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));

        aekran_kul_adı.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aekran_kul_adı.setText("Kullanıcı Adı : ");

        aekran_sifre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aekran_sifre.setText("          Şifre :");

        kayitet_kadi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitet_kadi_alaniActionPerformed(evt);
            }
        });

        kayitet_sifre_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitet_sifre_alaniActionPerformed(evt);
            }
        });

        kayitet_kayıtol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kayitet_kayıtol.setText("KAYIT OL");
        kayitet_kayıtol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitet_kayıtolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aekran_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aekran_kul_adı, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kayitet_kadi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(kayitet_sifre_alani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(kayitet_kayıtol, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aekran_kul_adı, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayitet_kadi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aekran_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(kayitet_sifre_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(kayitet_kayıtol, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayitet_kadi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitet_kadi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kayitet_kadi_alaniActionPerformed

    private void kayitet_sifre_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitet_sifre_alaniActionPerformed

    }//GEN-LAST:event_kayitet_sifre_alaniActionPerformed

    private void kayitet_kayıtolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitet_kayıtolActionPerformed

        try {
            
            KayitEt kayitet = new KayitEt(kayitet_kadi_alani.getText(), kayitet_sifre_alani.getText());
            
            
            if(kayitet.kontrolEt()==false){
                
                VeriYazmaIslemleri.veriYaz(kayitet_kadi_alani.getText(), kayitet_sifre_alani.getText());
                
                JOptionPane.showMessageDialog(KayitEkrani.this,"Kayıt Olundu");
                
                setVisible(false);
                
            }
            else{
                JOptionPane.showMessageDialog(KayitEkrani.this,"Zaten Kayıtlı");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KayitEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_kayitet_kayıtolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aekran_kul_adı;
    private javax.swing.JLabel aekran_sifre;
    private javax.swing.JTextField kayitet_kadi_alani;
    private javax.swing.JButton kayitet_kayıtol;
    private javax.swing.JTextField kayitet_sifre_alani;
    // End of variables declaration//GEN-END:variables
}
